import type { Carpet, ThreadCard } from "./types";

export const ORIGINS = ["全部", "波斯", "安纳托利亚", "高加索", "藏毯"] as const;

export const THREAD_CARDS: ThreadCard[] = [
  { id: "TC-01", name: "石榴红", hex: "#8c2f1b", material: "羊毛线" },
  { id: "TC-02", name: "赭石棕", hex: "#b45309", material: "羊毛线" },
  { id: "TC-03", name: "靛蓝", hex: "#1e3a8a", material: "羊毛线" },
  { id: "TC-04", name: "松石绿", hex: "#0f766e", material: "羊毛线" },
  { id: "TC-05", name: "米白", hex: "#efe7d2", material: "羊毛线" },
  { id: "TC-06", name: "藏红花金", hex: "#ca8a04", material: "羊毛线" },
  { id: "TC-07", name: "茜草绯红", hex: "#9f1239", material: "羊毛线" },
  { id: "TC-08", name: "栀子黄", hex: "#d97706", material: "蚕丝线" },
  { id: "TC-09", name: "青黛", hex: "#0f4c5c", material: "蚕丝线" },
  { id: "TC-10", name: "烟紫", hex: "#6d28d9", material: "蚕丝线" },
  { id: "TC-11", name: "象牙白", hex: "#f5f0e1", material: "棉经线" },
  { id: "TC-12", name: "墨黑", hex: "#1c1917", material: "棉经线" },
];

export const SEED_CARPETS: Carpet[] = [
  {
    id: "CAR-092",
    origin: "波斯",
    era: "约1960s",
    density: "38 结/平方英寸",
    material: "羊毛",
    dye: "植物染",
    motif: "medallion",
    summary: "边缘磨损待补线，中心奖章保存完整。",
    stage: "待检",
    marks: [],
    threadId: null,
    log: [{ id: "seed-092", at: Date.now() - 86400000 * 3, text: "收毯建档，等待初检。" }],
  },
  {
    id: "CAR-117",
    origin: "安纳托利亚",
    era: "约1940s",
    density: "42 结/平方英寸",
    material: "羊毛",
    dye: "植物染",
    motif: "geometric",
    summary: "中心纹样缺口，局部绒头倒伏。",
    stage: "待检",
    marks: [],
    threadId: null,
    log: [{ id: "seed-117", at: Date.now() - 86400000 * 2, text: "收毯建档，等待初检。" }],
  },
  {
    id: "CAR-138",
    origin: "藏毯",
    era: "约1970s",
    density: "50 结/平方英寸",
    material: "羊毛",
    dye: "矿物染",
    motif: "floral",
    summary: "局部褪色，需匹配靛蓝色卡。",
    stage: "待检",
    marks: [],
    threadId: null,
    log: [{ id: "seed-138", at: Date.now() - 86400000, text: "收毯建档，等待初检。" }],
  },
  {
    id: "CAR-156",
    origin: "高加索",
    era: "约1930s",
    density: "35 结/平方英寸",
    material: "羊毛",
    dye: "天然染",
    motif: "striped",
    summary: "长边流苏断纬，织带松散。",
    stage: "待检",
    marks: [],
    threadId: null,
    log: [{ id: "seed-156", at: Date.now() - 86400000 * 4, text: "收毯建档，等待初检。" }],
  },
  {
    id: "CAR-163",
    origin: "波斯",
    era: "约1980s",
    density: "45 结/平方英寸",
    material: "羊毛底 丝绒头",
    dye: "植物染",
    motif: "floral",
    summary: "右上角水渍褪色，丝绒头需顺色。",
    stage: "待检",
    marks: [],
    threadId: null,
    log: [{ id: "seed-163", at: Date.now() - 86400000 * 5, text: "收毯建档，等待初检。" }],
  },
  {
    id: "CAR-171",
    origin: "安纳托利亚",
    era: "约1950s",
    density: "40 结/平方英寸",
    material: "羊毛",
    dye: "植物染",
    motif: "geometric",
    summary: "边角磨损，菱格中缺两处绒头。",
    stage: "待检",
    marks: [],
    threadId: null,
    log: [{ id: "seed-171", at: Date.now() - 86400000 * 6, text: "收毯建档，等待初检。" }],
  },
];
